spool VoyageTables
prompt LesVilles
select *
from agence.LesVilles;
prompt LesMonuments
select * 
from agence.LesMonuments;
prompt LesCircuits
select * 
from agence.LesCircuits;
prompt LesEtapes
select *
from agence.LesEtapes;
prompt LesProgrammations
select *
from agence.LesProgrammations;
prompt LesReservations
select *
from agence.LesReservations;
spool off;
