spool GrandeBouffeTables
prompt LesRepas
select *
from repas.LesRepas;
prompt LeMenu
select * 
from repas.LeMenu;
prompt LesPreferences
select * 
from repas.LesPreferences;
prompt LesPlats
select *
from repas.LesPlats;
spool off;
